---
title: "examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(clusterAnalysisUtils)
library(dplyr)
```



```{r show clustering parsing and mergging with upper level cluster}
cl1 <- system.file("extdata", "BIGSdb_038315_3800442768_50390.nogap.derep.uc", package="clusterAnalysisUtils")
cl2 <- system.file("extdata", "BIGSdb_038315_3800442768_50390.nogap.derep.swarm.uc", package="clusterAnalysisUtils")

cl1o <- clusterAnalysisUtils::clusterDataParser$new(fileName = cl1,format = "UC",remove_sizes = T)
cl2o <- clusterAnalysisUtils::clusterDataParser$new(fileName = cl2,format = "UC",remove_sizes = T)
new_clusters <- cl2o$seq_rep[cl1o$df$Cluster]
length(unique(cl1o$df$Member))
length(unique(cl1o$df$Cluster))
length(unique(new_clusters))
cl1o$add_upper_lever_clusters(cl2o)
length(unique(cl1o$df$Cluster))

```


```{r show joining two subsequent clustering}
new_clusters <- cl2o$seq_rep[cl1o$df$Cluster]
length(unique(cl1o$df$Member))
length(unique(cl1o$df$Cluster))
length(unique(new_clusters))
cl1o$add_upper_lever_clusters(cl2o)
length(unique(cl1o$df$Cluster))

```


```{r show parsing of different formats}
#tt <- "./set4test/set1.derep.swarm.out"
cl3 <- system.file("extdata", "set1.derep.swarm.out", package="clusterAnalysisUtils")
cl3o <- clusterAnalysisUtils::clusterDataParser$new(fileName = cl3,format = "MT",remove_sizes = T)

cl4 <- system.file("extdata", "set1.derep.swarm.uc", package="clusterAnalysisUtils")
cl4o <- clusterAnalysisUtils::clusterDataParser$new(fileName = cl4,format = "UC",remove_sizes = T)

cl3o$df
cl4o$df
```
